# Generated by Django 4.0.3 on 2022-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(default='', max_length=10)),
                ('feedback', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(default='', max_length=10)),
                ('notification', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=10)),
                ('productname', models.CharField(default='', max_length=10)),
                ('quantity', models.CharField(default='', max_length=10)),
                ('price', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('adharnumber', models.CharField(default='', max_length=10)),
                ('housenumber', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=10)),
                ('village', models.CharField(default='', max_length=10)),
                ('localtype', models.CharField(default='', max_length=10)),
                ('taluk', models.CharField(default='', max_length=10)),
                ('localname', models.CharField(default='', max_length=10)),
                ('mobileno', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=10)),
                ('cardnumber', models.CharField(default='', max_length=10)),
                ('cardtype', models.CharField(default='', max_length=10)),
                ('photo', models.FileField(default='', upload_to='images')),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('cardnumber', models.CharField(default='', max_length=10)),
                ('cardtype', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
